In [1]:
import pandas as pd

In [6]:
gastos = pd.read_csv('gastos.csv')
gastos

     ENERO  FEBRERO    MARZO    ABRIL     MAYO    JUNIO
0  34566.0  12455.0   8222.0  12444.0  19023.0  12456.0
1      NaN  23456.0      NaN      NaN  22000.0  23477.0
2  23444.0  12668.0  14556.0  35667.0  21000.0  11456.0
3   9444.0  11000.0  10993.0  12889.0      NaN      NaN
4  12455.0      NaN  13452.0      NaN      NaN  10344.0

In [ ]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)

gastos_imputed = pd.DataFrame(imputer.fit_transform(gastos), columns=gastos.columns)
gastos_imputed

     ENERO  FEBRERO    MARZO    ABRIL     MAYO    JUNIO
0  34566.0  12455.0   8222.0  12444.0  19023.0  12456.0
1  29005.0  23456.0  11389.0  24055.5  22000.0  23477.0
2  23444.0  12668.0  14556.0  35667.0  21000.0  11456.0
3   9444.0  11000.0  10993.0  12889.0  20511.5  16910.5
4  12455.0  11834.0  13452.0  24278.0  21500.0  10344.0